# Left my API info in here for your convenience in playing with the app...
# Please don't abuse!
client_id: '329628485114-m68o4644g176qm48vg97q0c5v3tsrqf0.apps.googleusercontent.com'
client_secret: 'm-h1D1GPMyv08r-zIbj6eBkO'
